const http=require('http');const fs=require('fs');const path=require('path');const {Server}=require('socket.io');
const PORT=process.env.PORT||3000;const root=__dirname;const rooms=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
const server=http.createServer((req,res)=>{let u=(req.url||'/').split('?')[0];if(u==='/')u='/index.html';const file=path.join(root,path.normalize(u));if(!file.startsWith(root)){res.writeHead(403);return res.end('Forbidden')}fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(d)})});
const io=new Server(server,{cors:{origin:'*',methods:['GET','POST']},maxHttpBufferSize:1e6});
function code(){let s='';do{s=Math.random().toString(36).slice(2,7).toUpperCase()}while(rooms.has(s));return s}
function leave(id){const s=io.sockets.sockets.get(id);if(!s||!s.data.room)return;const r=rooms.get(s.data.room);if(r){r.players.delete(id);s.to(r.code).emit('playerLeft',{id});if(!r.players.size)rooms.delete(r.code)}}
io.on('connection',s=>{s.on('createRoom',d=>{leave(s.id);const c=code(),r={code:c,players:new Map};r.players.set(s.id,{id:s.id,name:String(d?.name||'Zippy').slice(0,16),x:0,y:0,z:500,ry:0,color:Math.floor(Math.random()*0xffffff)});rooms.set(c,r);s.join(c);s.data.room=c;s.emit('roomCreated',{room:c,players:[...r.players.values()]})});s.on('joinRoom',d=>{const c=String(d?.room||'').toUpperCase();const r=rooms.get(c);if(!r)return s.emit('roomError',{message:'Sala não encontrada.'});if(r.players.size>=8)return s.emit('roomError',{message:'Sala cheia (8 jogadores).'});leave(s.id);r.players.set(s.id,{id:s.id,name:String(d?.name||'Zippy').slice(0,16),x:0,y:0,z:500,ry:0,color:Math.floor(Math.random()*0xffffff)});s.join(c);s.data.room=c;s.emit('roomJoined',{room:c,players:[...r.players.values()]});s.to(c).emit('playerJoined',r.players.get(s.id))});s.on('move',p=>{const r=rooms.get(s.data.room);const me=r?.players.get(s.id);if(!me||!p)return;me.x=Number(p.x)||0;me.y=Number(p.y)||0;me.z=Number(p.z)||0;me.ry=Number(p.ry)||0;s.to(r.code).emit('playerMoved',{id:s.id,x:me.x,y:me.y,z:me.z,ry:me.ry})});s.on('disconnect',()=>leave(s.id))});
server.listen(PORT,()=>console.log('Zippy World server listening on '+PORT));
